-- return {
--   {
--     "echasnovski/mini.indentscope",
--     opts = {
--       options = {
--         try_as_border = true,
--         border = "both",
--       },
--       draw = {
--         animation = require("mini.indentscope").gen_animation.linear({ duration = 1 }),
--       },
--     },
--   },
-- }
--
return {}
